# Generated by Django 3.2.5 on 2021-09-08 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_subject_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='Subject_code',
            new_name='subject_code',
        ),
    ]
